TrajectoryPlannerROS:
  max_vel_x: 0.50
  min_vel_x: 0.05
  max_vel_theta: 12.56
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 6.28
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  meter_scoring: true