obstacle_range: 1.0
raytrace_range: 3.0
footprint: [[-0.05, -0.05], [-0.05, 0.05], [0.05, 0.05], [0.05, -0.05]]
#robot_radius: ir_of_robot
inflation_radius: 0.15
#max_obstacle_height: 3.0
#min_obstacle_height: -3.0
#inf_is_valid: true

observation_sources: scan

scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
